### ISSUE TITLE
几个使用的问题

### ISSUE THREAD

**Issue by ZJJDJJ** [YXL76/WeChat-ChatRoom#2]
1、在‘’将client文件夹导入微信开发者工具‘’这一步提示了要含有app.json的文件才可以导入，而client里面不包含，怎么破？
2、没找到chat.js这个文件。。
求大佬帮忙解答下

**Comment by YXL76** [comment]
1. 现在使用[mpx](https://github.com/didi/mpx)，所以要先构建，会生成一个`dist`文件夹，就可以导入了，可以查看https://github.com/YXL76/WeChat-ChatRoom/blob/master/client/README.md
2. 文档没更新，现在是修改`src/pages/chat/chat/chat.mpx`里`wx.connectSocket`的`url`

**Comment by YXL76** [comment]
> 1、在‘’将client文件夹导入微信开发者工具‘’这一步提示了要含有app.json的文件才可以导入，而client里面不包含，怎么破？
> 2、没找到chat.js这个文件。。
> 求大佬帮忙解答下

1. 现在使用[mpx](https://github.com/didi/mpx)，所以要先构建，会生成一个`dist`文件夹，就可以导入了，可以查看https://github.com/YXL76/WeChat-ChatRoom/blob/master/client/README.md
2. 文档没更新，现在是修改`src/pages/chat/chat/chat.mpx`里`wx.connectSocket`的`url`
